using UnityEngine;
using Unity.Robotics.ROSTCPConnector;
using RosMessageTypes.Sensor;

public class SensorCameraImageSubscriber : MonoBehaviour
{
    public string topicName = "/client1/theta_image";
    public Skybox skybox;
    public float displayFrequency = 72.0f; // Up to 90Hz?
    private Texture2D texture2D;
    public bool isImageReceived = true;
    private bool SkyChanged = true;
    private bool isSubscribed = false;
    private ROSConnection rosConnection;
    private Vector3 PosOrigin;
    private bool IsVRorKey;

    public Material defaultSkyboxMaterial;

    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

        if ((Input.GetKey(KeyCode.B) || OVRInput.GetDown(OVRInput.RawButton.B)) && isImageReceived == false)
        {
            isImageReceived = true;
        }
        if (isImageReceived == true && SkyChanged != isImageReceived)
        {
            ResetSkybox(); 
            Unsubscribe();
            ResetCameraPosition();
        }
        else if (isImageReceived == false && SkyChanged != isImageReceived)
        {
            texture2D = new Texture2D(1, 1);
            texture2D.Apply();
            OVRPlugin.systemDisplayFrequency = displayFrequency;
            DisplayImage(); 
            Subscribe();
            ChangeCameraPosition();
        }
        SkyChanged = isImageReceived;
    }


    private void RenderThetaImage(CompressedImageMsg msg)
    {
        Debug.Log("Received Theta Image Message");

        if (isImageReceived == false)
        {
            texture2D.LoadImage(msg.data);

            skybox.material = new Material(Shader.Find("Skybox/Panoramic"));
            // skyboxïŋ―Éeïŋ―Nïŋ―Xïŋ―`ïŋ―ïŋ―ïŋ―ïŋ―Ýïŋ―
            skybox.material.SetTexture("_MainTex", texture2D);

        }
    }

    // ïŋ―ïŋ―Mïŋ―ïŋ―ïŋ―ïŋ―ïŋ―æïŋ―ïŋ―\ïŋ―ïŋ―ïŋ―ïŋ―ïŋ―éïŋ―\ïŋ―bïŋ―h
    private void DisplayImage()
    {
        skybox.material = new Material(Shader.Find("Skybox/Panoramic"));
        skybox.material.SetTexture("_MainTex", texture2D); // skyboxïŋ―ÉTïŋ―uïŋ―Xïŋ―Nïŋ―ïŋ―ïŋ―Cïŋ―uïŋ―ïŋ―ïŋ―ïŋ―ïŋ―æïŋ―ïŋ―ïŋ―Zïŋ―bïŋ―g
    }

    // ïŋ―fïŋ―tïŋ―Hïŋ―ïŋ―ïŋ―gïŋ―ïŋ―Skyboxïŋ―Éßïŋ―ïŋ―ïŋ―ïŋ―\ïŋ―bïŋ―h
    private void ResetSkybox()
    {
        skybox.material = defaultSkyboxMaterial; // ïŋ―ïŋ―ïŋ―ïŋ―ïŋ―Ýčĩïŋ―Äïŋ―ïŋ―Čïŋ―Skyboxïŋ―Éßïŋ―
    }

    // ïŋ―Tïŋ―uïŋ―Xïŋ―Nïŋ―ïŋ―ïŋ―Cïŋ―uïŋ―ïŋ―ïŋ―Jïŋ―nïŋ―ïŋ―ïŋ―éïŋ―\ïŋ―bïŋ―h
    private void Subscribe()
    {
        if (!isSubscribed)
        {
            if (topicName != null)
            {
                rosConnection = ROSConnection.GetOrCreateInstance();
                rosConnection.Subscribe<CompressedImageMsg>(topicName, RenderThetaImage);
                isSubscribed = true;
                Debug.Log("Subscribed to the topic: " + topicName);
            }
            else
            {
                Debug.Log("Subscribed topic name is null");
            }
        }
    }

    // ïŋ―Tïŋ―uïŋ―Xïŋ―Nïŋ―ïŋ―ïŋ―Cïŋ―uïŋ―ïŋ―ïŋ―~ïŋ―ïŋ―ïŋ―éïŋ―\ïŋ―bïŋ―h
    private void Unsubscribe()
    {
        if (isSubscribed)
        {
            if (topicName != null)
            {
                rosConnection.Unsubscribe(topicName);
                Debug.Log("Unsubscribed from the topic: 1 : " + topicName);
                isSubscribed = false;
                Debug.Log("Unsubscribed from the topic: " + topicName);
                //  rosConnection = null;
            }
        }
    }

    private void ChangeCameraPosition()
    {
        PosOrigin = GameObject.Find("OVRPlayerController").transform.position;
        if (GameObject.Find("OVRPlayerController").GetComponent<CharacterController>().enabled == true) 
        {
            IsVRorKey = true;
        }
        GameObject.Find("OVRPlayerController").GetComponent<CharacterController>().enabled = false;
        GameObject.Find("OVRPlayerController").GetComponent<Collider>().enabled = false;
        GameObject.Find("OVRPlayerController").transform.position = new Vector3(0.0f,10000.0f,0.0f);
    }

    private void ResetCameraPosition()
    {
        GameObject.Find("OVRPlayerController").transform.position = PosOrigin;
        if (IsVRorKey == true)
        {
            GameObject.Find("OVRPlayerController").GetComponent<CharacterController>().enabled = true;
            GameObject.Find("OVRPlayerController").GetComponent<Collider>().enabled = true;
        }
    }
}
